FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build

WORKDIR /app

COPY . /app

RUN dotnet publish -c Release -r debian.9-x64 -f netcoreapp2.2 MemoryLeak.2.2.fsproj

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as debug_tools

# lldb version is 7, which is ok
RUN apt update && apt install lldb -y

ENV TOOL_VERSION=3.0.0-preview9.19454.1

# install dotnet tools for dump and sos
ENV PATH=$PATH:$HOME/.dotnet/tools
RUN dotnet tool install -g dotnet-symbol
RUN dotnet tool install -g dotnet-sos --version ${TOOL_VERSION} && ~/.dotnet/tools/dotnet-sos install
RUN dotnet tool install -g dotnet-dump --version ${TOOL_VERSION}
RUN dotnet tool install -g dotnet-trace --version ${TOOL_VERSION}

FROM debug_tools

COPY --from=build  /app/bin/Release/netcoreapp2.2/debian.9-x64/publish /app

ENV PATH=/root/.dotnet/tools:$PATH

WORKDIR /app

CMD [ "./MemoryLeak.2.2" ]